"""adds nhl api columns to teams

Revision ID: 3014ce965ab9
Revises: d0dccda8cee1
Create Date: 2025-12-14 10:02:51.556688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3014ce965ab9'
down_revision: Union[str, Sequence[str], None] = 'd0dccda8cee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('api_web_nhle_abr', sa.String(length=3), nullable=True))
    op.add_column('teams', sa.Column('api_nhle_id', sa.Integer(), nullable=True))
    op.alter_column('teams', 'abbreviation',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.drop_constraint(op.f('teams_abbreviation_key'), 'teams', type_='unique')
    op.create_index(op.f('ix_teams_api_nhle_id'), 'teams', ['api_nhle_id'], unique=True)
    op.create_index(op.f('ix_teams_api_web_nhle_abr'), 'teams', ['api_web_nhle_abr'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_api_web_nhle_abr'), table_name='teams')
    op.drop_index(op.f('ix_teams_api_nhle_id'), table_name='teams')
    op.create_unique_constraint(op.f('teams_abbreviation_key'), 'teams', ['abbreviation'], postgresql_nulls_not_distinct=False)
    op.alter_column('teams', 'abbreviation',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.drop_column('teams', 'api_nhle_id')
    op.drop_column('teams', 'api_web_nhle_abr')
    # ### end Alembic commands ###
