"""remove unique check on api_web_nhle_abr

Revision ID: 3800a3f8ee3f
Revises: 76dc0181c868
Create Date: 2025-12-14 10:52:09.742884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3800a3f8ee3f'
down_revision: Union[str, Sequence[str], None] = '76dc0181c868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_api_web_nhle_abr'), table_name='teams')
    op.create_index(op.f('ix_teams_api_web_nhle_abr'), 'teams', ['api_web_nhle_abr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_api_web_nhle_abr'), table_name='teams')
    op.create_index(op.f('ix_teams_api_web_nhle_abr'), 'teams', ['api_web_nhle_abr'], unique=True)
    # ### end Alembic commands ###
