"""fixes city column on teams

Revision ID: d9682e5ab80d
Revises: 3014ce965ab9
Create Date: 2025-12-14 10:48:31.555967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9682e5ab80d'
down_revision: Union[str, Sequence[str], None] = '3014ce965ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'abbreviation',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'abbreviation',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    # ### end Alembic commands ###
